"""Initial migration

Revision ID: 0fe7c93f8899
Revises: 
Create Date: 2025-08-22 21:34:22.838065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe7c93f8899'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trademarks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trademarks_id'), 'trademarks', ['id'], unique=False)
    op.create_index(op.f('ix_trademarks_name'), 'trademarks', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trademarks_name'), table_name='trademarks')
    op.drop_index(op.f('ix_trademarks_id'), table_name='trademarks')
    op.drop_table('trademarks')
    # ### end Alembic commands ###
